name: CafeMC
version: '0.1.0'
main: dev.lizainslie.cafemc.CafeMC
api-version: '1.21'

depend:
  - DiscordSRV
  - TAB
  - Vault

permissions: 
  cafe.tpa.use:
    description: Teleport to a player & accept/deny requests
  cafe.tpa.back:
    description: Teleport back to your previous location
  cafe.afk:
    description: Toggle AFK status
  cafe.rename:
    description: Rename the item in your hand
  cafe.home:
    description: Teleport to & set your home
  cafe.balance:
    description: Check your balance
  cafe.balance.others:
    description: Check the balance of another player
  cafe.pay:
    description: Pay another player
  cafe.deposit:
    description: Deposit your valuables as money into your account

commands:
  tpa:
    description: Teleport to a player
    usage: /<command> <player>
    permission: cafe.tpa.use
  tpaccept:
    description: Accept a teleport request
    usage: /<command>
    permission: cafe.tpa.use
  tpdeny:
    description: Deny a teleport request
    usage: /<command>
    permission: cafe.tpa.use
  back:
    description: Teleport back to your previous location
    usage: /<command>
    permission: cafe.tpa.back
  afk:
    description: Toggle AFK status
    usage: /<command>
    permission: cafe.afk
  rename:
    description: Rename the item in your hand
    usage: /<command> <name>
    permission: cafe.rename
  home:
    description: Teleport to & set your home
    usage: /<command> [set|clear]
    permission: cafe.home
  migrate:
    description: Migrate database changes
    usage: /<command>
  balance:
    description: Check your balance or the balance of another player
    usage: /<command> [player]
    permission: cafe.balance
    aliases: 
      - bal
  pay:
    description: Pay another player
    usage: /<command> <player> <amount>
    permission: cafe.pay
  deposit:
    description: Deposit your valuables as money into your account
    usage: /<command>
    permission: cafe.deposit
#  warp:
#    description: Teleport to a warp
#    usage: /<command> <warp>
#  setwarp:
#    description: Set a warp
#    usage: /<command> <warp>
#    permission: cafemc.warp.set
#  delwarp:
#    description: Delete a warp
#    usage: /<command> <warp>
#    permission: cafemc.warp.delete
#  warps:
#    description: List all warps
#    usage: /<command>
#  playerwarp:
#    description: Manage your player warps
#    usage: /<command> <create|delete>
#    permission: cafemc.playerwarp
#  pwarp:
#    description: Teleport to a player warp
#    usage: /<command> <player>